{% set name = "munge" %}
{% set version = "0.5.15" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dun/munge/releases/download/{{ name }}-{{ version }}/{{ name }}-{{ version }}.tar.xz
  sha256: 3f979df117a34c74db8fe2835521044bdeb08e3b7d0f168ca97c3547f51da9ba

build:
  error_overdepending: true
  error_overlinking: true
  number: 0
  skip: true  # [not linux]

requirements:
  build:
    - {{ compiler('c') }}
    - {{ stdlib('c') }}
    - make  # [unix]
  host:
    - bzip2
    - openssl
    - zlib

test:
  commands:
    - munge --help
    - remunge --help
    - unmunge --help

about:
  home: https://dun.github.io/munge/
  dev_url: https://github.com/dun/munge
  doc_url: https://dun.github.io/munge/
  license: LGPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: MUNGE (MUNGE Uid 'N' Gid Emporium) is an authentication service for creating and validating credentials
  description: |
    MUNGE (MUNGE Uid 'N' Gid Emporium) is an authentication service for
    creating and validating credentials.  It is designed to be highly
    scalable for use in an HPC cluster environment.  It allows a process
    to authenticate the UID and GID of another local or remote process
    within a group of hosts having common users and groups. These hosts
    form a security realm that is defined by a shared cryptographic key.
    Clients within this security realm can create and validate credentials
    without the use of root privileges, reserved ports, or platform-specific
    methods.

extra:
  recipe-maintainers:
    - duncanmmacleod
