{% set name = "munge" %}
{% set version = "0.5.14" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/dun/munge/releases/download/{{ name }}-{{ version }}/{{ name }}-{{ version }}.tar.xz
  sha256: 6606a218f18090fa1f702e3f6fb608073eb6aafed534cf7dd81b67b2e0d30640

build:
  number: 0
  skip: true  # [win]

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - bzip2
    - openssl
    - zlib

test:
  requires:
    - pkg-config  # [unix]
  commands:
    - munge --help
    - remunge --help
    - unmunge --help
    - pkg-config --print-errors --modversion munge  # [unix]

about:
  home: https://dun.github.io/munge/
  dev_url: https://github.com/dun/munge
  doc_url: https://dun.github.io/munge/
  license: LGPL-3.0-or-later
  license_family: GPL
  license_file: COPYING
  summary: MUNGE (MUNGE Uid 'N' Gid Emporium) is an authentication service for creating and validating credentials
  description: |
    MUNGE (MUNGE Uid 'N' Gid Emporium) is an authentication service for
    creating and validating credentials.  It is designed to be highly
    scalable for use in an HPC cluster environment.  It allows a process
    to authenticate the UID and GID of another local or remote process
    within a group of hosts having common users and groups. These hosts
    form a security realm that is defined by a shared cryptographic key.
    Clients within this security realm can create and validate credentials
    without the use of root privileges, reserved ports, or platform-specific
    methods.

extra:
  recipe-maintainers:
    - duncanmmacleod
