travis:
  secure:
    BINSTAR_TOKEN: GLzuM/HLnXD0Wa/sHBZyDFH8xCNWXBKawPlVAfsQIateJph3ZWynBdUGsOtMSu8roTx7yM5KwpbNBmPI5C5KMb0Ape344BP7xRTLYPV241fq9gLgsz5Ypw7s5RULtjOuLMaA/FxBcV7bj+rwFv38kGAGSg3CvbT/5ZV1+3IFA6zFEFRgQXiam/MqOoRXVm29IXQ7spwdh+vcgZVAy0rLYDSYFTO7S5pbkULfmkvJtodBgBuJSwMuEX94DNESC7H1qsqB13Ezv7qHwLtlAip1rCC05muDU7mohIlZDAyv1vFNaOkEtdT3acINHAID6v7PysOwWt64fYDkHlsRqfQCcQLLoPS8eexO48IKG8zCaJscxhqzCoMLbnnql2gR/XX6zIPRk4sX3Rpy0rqm98ffJS9iz0YnVrSeUc28/qAstRld1pOD7fVBc1ibKJULGmfJFRCdtHknpUJQ+jAK1Ggaw2PuZxzFIR/ZilwG38oh1Yfhh8CwBnLZXjV8aj0YNOJ+nFjbK8r2/VNz2xN36YyLorjfPxbjZi7RrHNvu5PHW/Gi0MTBvs6F4DlKnbkzoR0wFp9Nmdt9VZsxZnIbkx4g8nI4WUePFl1xAdBLx93wpIUsU+DwzylNuVttc2xb0oa5IFHBKCllt91908QS1d4uqqLccv+dacBD/5VKHxIi8eY=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
